# Generated by Django 5.1.1 on 2024-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
