# Generated by Django 5.1.1 on 2024-09-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0004_variation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
